name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.x'

    - name: Install dependencies
      run: |
        R -e "install.packages('shiny')"

    - name: Deploy Shiny App
      run: R -e "shiny::runApp(appDir = '.')"
